name: Build Executables

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # Step 5: Build Executables with PyInstaller (Linux)
      - name: Build Executable with PyInstaller (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile xml-diff.py
          pyinstaller --onefile xml-patch.py
        shell: bash

      # Step 6: Build Executables with PyInstaller (Windows)
      - name: Build Executable with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile xml-diff.py
          pyinstaller --onefile xml-patch.py
        shell: powershell

      # Step 7: Upload Executables as Artifacts
      - name: Upload Executables as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executables-${{ matrix.os }}
          path: |
            dist/xml-diff${{ matrix.os == 'windows-latest' && '.exe' || '' }}
            dist/xml-patch${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # Step 8: Attach Linux Diff Executable to Release
      - name: Attach Linux Diff Executable to Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          files: ./dist/xml-diff
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # Step 9: Attach Linux Patch Executable to Release
      - name: Attach Linux Patch Executable to Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          files: ./dist/xml-patch
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # Step 10: Attach Windows Diff Executable to Release
      - name: Attach Windows Diff Executable to Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        with:
          files: ./dist/xml-diff.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      # Step 11: Attach Windows Patch Executable to Release
      - name: Attach Windows Patch Executable to Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        with:
          files: ./dist/xml-patch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}