name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Release Please Action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python  # Specifies that it's a Python project
          # Optional configurations:
          # version-file: setup.py  # Specify the version file if different
          # bump-minor-pre-major: true
          # monorepo-tags: true
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
