name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout the repository
      -
        name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      # Step 2: Release Please Action
      -
        name: Release Please Action
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python  # Specifies that it's a Python project
          # Optional configurations:
          # version-file: setup.py  # Specify the version file if different
          # bump-minor-pre-major: true
          # monorepo-tags: true
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
