name: Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Nuitka
      - name: Install Nuitka
        run: |
          python -m pip install nuitka

      # Step 5: Build Executables with Nuitka
      - name: Build Executable with Nuitka
        run: |
          python -m nuitka --mingw64 xml-diff.py --assume-yes-for-downloads --standalone
          python -m nuitka --mingw64 xml-patch.py --assume-yes-for-downloads --standalone
          ls -l .
        shell: powershell

      # Step 6: Upload Executables as Artifacts
      - name: Upload Executables as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables-upload
          path: |
            xml-diff.dist/xml-diff.exe
            xml-patch.dist/xml-patch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}


      # Step 9: Scan with VirusTotal
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          # update_release_body: true
          vt_api_key: ${{ secrets.VT_API_KEY }}
          github_token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          request_rate: 4
          files: |
            .exe$
